# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=64)),
                ('seq_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HaftarahReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(choices=[('mp3', 'mp3'), ('pdf', 'pdf'), ('jpg', 'jpg')], default='mp3', max_length=3)),
                ('s3_obj_key', models.CharField(max_length=2048)),
                ('seq_number', models.PositiveSmallIntegerField()),
                ('file_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ParshaName',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=64)),
                ('seq_number', models.PositiveSmallIntegerField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.BookName')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=64)),
                ('seq_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('display', models.CharField(max_length=128)),
                ('s3_obj_key', models.CharField(max_length=2048)),
                ('extension', models.CharField(choices=[('mp3', 'mp3'), ('pdf', 'pdf'), ('jpg', 'jpg')], default='mp3', max_length=3)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('seq_number', models.PositiveSmallIntegerField()),
                ('file_name', models.CharField(max_length=128)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.ServiceName')),
            ],
        ),
        migrations.CreateModel(
            name='TorahReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triennial', models.CharField(choices=[(None, None), ('1st', '1st Triennial'), ('2nd', '2nd Triennial'), ('3rd', '3rd Triennial')], default='1st', max_length=3)),
                ('aliyah', models.CharField(choices=[(None, None), ('1st', '1st Aliyah'), ('2nd', '2nd Aliyah'), ('3rd', '3rd Aliyah'), ('4th', '4th Aliyah'), ('5th', '5th Aliyah'), ('6th', '6th Aliyah'), ('7th', '7th Aliyah'), ('Maftir', 'Maftir')], default='1st', max_length=6)),
                ('extension', models.CharField(choices=[('mp3', 'mp3'), ('pdf', 'pdf'), ('jpg', 'jpg')], default='mp3', max_length=3)),
                ('s3_obj_key', models.CharField(max_length=2048)),
                ('seq_number', models.PositiveSmallIntegerField()),
                ('file_name', models.CharField(max_length=128)),
                ('parsha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.ParshaName')),
            ],
        ),
        migrations.AddField(
            model_name='haftarahreading',
            name='parsha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.ParshaName'),
        ),
    ]
