# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20170502_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='haftarahreading',
            name='extension',
            field=models.CharField(choices=[('mp3', 'mp3'), ('pdf', 'pdf'), ('jpg', 'jpg'), ('png', 'png')], default='mp3', max_length=3),
        ),
        migrations.AlterField(
            model_name='song',
            name='extension',
            field=models.CharField(choices=[('mp3', 'mp3'), ('pdf', 'pdf'), ('jpg', 'jpg'), ('png', 'png')], default='mp3', max_length=3),
        ),
        migrations.AlterField(
            model_name='torahreading',
            name='extension',
            field=models.CharField(choices=[('mp3', 'mp3'), ('pdf', 'pdf'), ('jpg', 'jpg'), ('png', 'png')], default='mp3', max_length=3),
        ),
    ]
